linters-settings:

  funlen:
    lines: -1
    statements: 40

  staticcheck:
    checks: ["all"]

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package

linters:
  enable:
    - govet            # Reports suspicious constructs
    - goconst          # Checks for code formatting issues
    - gosec            # Identifies potential security issues in the code
    - unused           # Checks for unused variables, constants, etc.
    - staticcheck      # Static analysis tool which finds bugs, performance issues, and more
    - gosimple         # Suggests simplifications to the code
    - errcheck         # Checks that you are handling errors
    - funlen           # Finds repeated strings that could be replaced by a constant
    - depguard         # Restrict the use of certain packages
    - gofumpt          # Check for import ordering

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # Disable function length check for test files

run:
  timeout: 5m
  tests: true
  config: .golangci.yml
  issues-exit-code: 1
  new: false

output:
  formats:
    - format: colored-line-number

severity:
  default-severity: error
  min-severity: warning

exclude:
  - ST1000             # Overrides EXC0002, to stop warning about requiring a comment on packages

include:
  - EXC0002            # Enforce comments on exported functions

max-issues-per-linter: 0  # No limit on the number of issues per linter
max-same-issues: 0         # No limit on the number of identical issues
