name: Lint Check

on:
  push:
    branches:
      - main
    paths:
      - 'go-projects/**/*.go'  # Only trigger when .go files in go-projects/ are modified
  pull_request:
    branches:
      - main
    paths:
      - 'go-projects/**/*.go'  # Only trigger when .go files in go-projects/ are modified
  workflow_dispatch:           # Allow manual trigger

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # This checks out the code

      - name: Set up Go
        uses: actions/setup-go@v5   # This sets up the Go environment
        with:
          go-version: '1.22'        # Specify the Go version you want to use

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
          golangci-lint --version  # Verify installation

      - name: Run golangci-lint
        run: |
          cd go-projects/subscription-service  # Change to the correct directory
          golangci-lint run --timeout=5m  # Run the linter
